### PR TITLE
Asynchronize revise flow

### PR DESCRIPTION
**Pull request by Mirv**
The check has to run no matter what, could probably run as one liner

### CODE REVIEW

**Comment by Mirv** [comment]
Interesting ... Travis is failing says it's hanging ... I don't have or use this server for CI ... so not sure how to fix ... but it works on my machine? 

```
mirv:~/workspace (asynchronizeReviseFlow) $ rake
Run options: --seed 4701

# Running:

................

Finished in 0.008252s, 1938.9277 runs/s, 2060.1107 assertions/s.

16 runs, 17 assertions, 0 failures, 0 errors, 0 skips
Coverage report generated for RSpec to /home/ubuntu/workspace/coverage. 36 / 36 LOC (100.0%) covered.
```

**Comment by iCodeSometime** [comment]
Right, it's not you. Travis broke sometime this morning for JRuby only.. Not sure yet what the problem could be, the commit that broke it did nothing but remove comments.

**Comment by Mirv** [comment]
This commit is in regards to removing the `next unless <condition>` ... are you thinking of the comment only commit I did before?

**Comment by iCodeSometime** [comment]
Travis should be good now.. I removed jruby till I can figure out why it's broken.
Went ahead and pushed it through :)

**Pull request merged**
