### PR TITLE
Backwards compatibility + 2 minor

### PR DESCRIPTION
**Pull request by Mirv**
- Reverting to #send for add_method for pre-ruby 2.5
- use of #last over `-1`
- added an extra `#` to comment block to make it match style

### CODE REVIEW

**Comment by Mirv** [comment]
```
mirv:~/workspace (version2asyncAssigning) $ rake
Run options: --seed 23091

# Running:

.............

Finished in 0.005981s, 2173.5409 runs/s, 2507.9318 assertions/s.

13 runs, 15 assertions, 0 failures, 0 errors, 0 skips
Coverage report generated for RSpec to /home/ubuntu/workspace/coverage. 20 / 21 LOC (95.24%) covered.

```

**Review by iCodeSometime — APPROVED** [review]
Thanks!

**Comment by Mirv** [comment]
What was this one doing in travis-CI?

**Comment by iCodeSometime** [comment]
Ruby 2.2.2 and jruby dislike calling super from inside the define_method block. I think I have a fix, just need to test it out

**Pull request merged**
